background #05040A
foreground #F2EEFF

selection_background #2B1E52
selection_foreground #FFFFFF

cursor #B26BFF
cursor_text_color #05040A

url_color #D7C1FF

active_border_color #9D6BFF
inactive_border_color #231B38

active_tab_background #171029
active_tab_foreground #FFFFFF
inactive_tab_background #0A0812
inactive_tab_foreground #8A81A6

# ANSI colors
color0 #05040A
color1 #FF6B8D
color2 #4FD39B
color3 #FFC966
color4 #83A7FF
color5 #B26BFF
color6 #71D2E8
color7 #E9E5F7

color8 #372E4D
color9 #FF8FAE
color10 #82EFC0
color11 #FFDA8A
color12 #A7C0FF
color13 #D0A4FF
color14 #98E3F4
color15 #FFFFFF
