monitor.alsa.rules = [
  {
    matches = [ { node.name = "~alsa_output.pci-0000_00_1f.*" } ]
    actions = { update-props = { priority.driver = 2000, priority.session = 2000 } }
  }
  {
    matches = [ { node.name = "~alsa_output.pci-0000_01_00.*" } ]
    actions = { update-props = { priority.driver = 10, priority.session = 10 } }
  }
]
