# ---------- CORE ----------
continue=true
file-allocation=falloc

# ---------- SPEED LIMITS ----------
max-overall-download-limit=15M
max-overall-upload-limit=15M

# ---------- CONNECTIONS ----------
max-connection-per-server=4
split=4
min-split-size=5M

# ---------- TORRENT ----------
enable-dht=true
seed-time=0
