#!/bin/sh
set -eu

msg() { printf '==> %s\n' "$*"; }
info() { printf '  -> %s\n' "$*"; }
skip() { printf '  -> [SKIP] %s\n' "$*"; }
done_msg() { printf '  -> [DONE] %s\n' "$*"; }

# 1. Detect btrfs filesystems
msg "Checking for btrfs filesystems..."
BTRFS_MOUNTS=$(findmnt -n -o TARGET -t btrfs 2>/dev/null || true)

if [ -z "$BTRFS_MOUNTS" ]; then
  skip "No btrfs filesystems detected. Nothing to do."
  exit 0
fi

info "Found btrfs mounts:"
echo "$BTRFS_MOUNTS" | while read -r m; do info "  $m"; done
echo ""

# 2. Install and enable cronie if not present
msg "Checking cron daemon..."
if ! command -v crontab >/dev/null 2>&1; then
  info "Installing cronie..."
  sudo pacman -S --noconfirm --needed cronie-openrc >/dev/null 2>&1
  done_msg "cronie installed"
else
  skip "cronie is already installed"
fi

# 3. Enable and start cronie service
if ! rc-service cronie status 2>/dev/null | grep -q "started"; then
  msg "Enabling cronie service..."
  sudo rc-update add cronie default 2>/dev/null || true
  sudo rc-service cronie start 2>/dev/null || true
  done_msg "cronie enabled and started"
else
  skip "cronie is already running"
fi

# 4. Create cron directories if they don't exist
CRON_DIR="/etc/cron.weekly"
if [ ! -d "$CRON_DIR" ]; then
  msg "Creating $CRON_DIR..."
  sudo mkdir -p "$CRON_DIR"
  done_msg "Directory created"
else
  skip "$CRON_DIR already exists"
fi

# 5. Backup fstab (only once)
FSTAB_BAK="/etc/fstab.bak.pre-btrfs-opt"
if [ ! -f "$FSTAB_BAK" ]; then
  msg "Backing up /etc/fstab..."
  sudo cp /etc/fstab "$FSTAB_BAK"
  done_msg "Backup saved to $FSTAB_BAK"
else
  skip "fstab backup already exists at $FSTAB_BAK"
fi

# 6. Optimize mount options for each btrfs mount
msg "Optimizing btrfs mount options..."

for mount_point in $BTRFS_MOUNTS; do
  info "Checking $mount_point..."

  # Get the current fstab line for this mount point
  fstab_line=$(grep -E "^[^#].*[[:space:]]${mount_point}[[:space:]]" /etc/fstab 2>/dev/null || true)

  if [ -z "$fstab_line" ]; then
    skip "$mount_point not found in fstab (might be a subvolume or tmpfs)"
    continue
  fi

  # Extract current options (4th field)
  current_opts=$(echo "$fstab_line" | awk '{print $4}')
  new_opts="$current_opts"
  changed=false

  # Check and add each option only if missing
  for opt in "compress=zstd:3" "noatime" "space_cache=v2" "discard=async"; do
    # For compress, check for any compress= variant
    case "$opt" in
      compress=*)
        if echo "$current_opts" | grep -q "compress="; then
          skip "$mount_point: compression already set"
          continue
        fi
        ;;
      *)
        if echo "$current_opts" | grep -q "$opt"; then
          skip "$mount_point: $opt already set"
          continue
        fi
        ;;
    esac

    new_opts="${new_opts},${opt}"
    changed=true
    done_msg "$mount_point: added $opt"
  done

  # Only write to fstab if something actually changed
  if [ "$changed" = true ]; then
    # Use awk for safe, precise replacement
    sudo awk -v mp="$mount_point" -v old="$current_opts" -v new="$new_opts" '
            $0 ~ "^[^#]" && $2 == mp {
                sub(old, new)
            }
            { print }
        ' /etc/fstab >/tmp/fstab.tmp
    sudo mv /tmp/fstab.tmp /etc/fstab
    done_msg "$mount_point: fstab updated"
  else
    skip "$mount_point: all options already optimal"
  fi
done

# 7. Set up periodic maintenance via cron
msg "Setting up btrfs maintenance cron jobs..."

CRON_FILE="/etc/cron.weekly/btrfs-maintenance"

if [ -f "$CRON_FILE" ]; then
  skip "btrfs maintenance cron job already exists at $CRON_FILE"
else
  # Collect btrfs device UUIDs for scrub
  BTRFS_UUIDS=$(lsblk -n -o UUID,FSTYPE 2>/dev/null | awk '$2=="btrfs" {print $1}' | sort -u || true)

  sudo tee "$CRON_FILE" >/dev/null <<'CRON_HEADER'
#!/bin/sh
# btrfs maintenance: weekly fstrim, scrub, and light balance
# Auto-generated by btrfs-optimizer.sh

# Weekly fstrim for all mounted filesystems (SSD health)
fstrim --all 2>/dev/null || true

CRON_HEADER

  # Add scrub commands for each btrfs UUID
  if [ -n "$BTRFS_UUIDS" ]; then
    for uuid in $BTRFS_UUIDS; do
      mount_target=$(findmnt -n -o TARGET -U "$uuid" 2>/dev/null || true)
      if [ -n "$mount_target" ]; then
        echo "btrfs scrub start -Bd \"$mount_target\" 2>/dev/null || true" | sudo tee -a "$CRON_FILE" >/dev/null
      fi
    done
    done_msg "Added btrfs scrub for $BTRFS_UUIDS"
  fi

  # Add light balance (only rebalances chunks that are less than 50% full)
  for mount_point in $BTRFS_MOUNTS; do
    echo "btrfs balance start -dusage=50 -musage=50 \"$mount_point\" 2>/dev/null || true" | sudo tee -a "$CRON_FILE" >/dev/null
  done
  done_msg "Added light btrfs balance"

  sudo chmod +x "$CRON_FILE"
  done_msg "Cron job created at $CRON_FILE"
fi

echo ""
msg "Btrfs optimization complete!"
info "Reboot to apply new mount options, or run: sudo mount -o remount /"
