unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g status-bg                           "#05040A"
set -gq @thm_bar_bg                        "#05040A"

set -gq @thm_bg                            "#05040A"
set -gq @thm_fg                            "#F2EEFF"
set -gq @thm_primary                       "#B26BFF"
set -gq @thm_inverse_primary               "#7C3AED"
set -gq @thm_surface_low                   "#0A0812"
set -gq @thm_surface                       "#171029"
set -gq @thm_surface_variant               "#2B1E52"
set -gq @thm_outline                       "#372E4D"
set -gq @thm_text_variant                  "#B6B0CC"

# --- UI Configuration ---

# General Status Layout
set -g status-position bottom
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=#{@thm_fg},bg=default"

# Left & Right Status
set -g status-left "#[fg=#{@thm_primary},bold]  #S #[fg=#{@thm_outline},nobold]│ "
set -g status-right "#[fg=#{@thm_text_variant}]%H:%M #[fg=#{@thm_outline}]│ #[fg=#{@thm_fg}]%d %b "

# Window Status (Inactive vs Active)
set -g window-status-separator ""
set -g window-status-format "#[fg=#{@thm_text_variant},nobold]  #I:#W  "
set -g window-status-current-format "#[fg=#{@thm_primary},bold]  #I:#W  "

# Pane Borders
set -g pane-border-style "fg=#{@thm_outline}"
set -g pane-active-border-style "fg=#{@thm_primary}"

# Command Messages & Copy Mode (High Contrast)
set -g message-style "fg=#{@thm_primary},bold"
set -g mode-style "fg=#{@thm_bg},bg=#{@thm_primary},bold"

# Style search highlights (when you search text using '/' in copy mode)
set -g copy-mode-match-style "fg=#{@thm_bg},bg=#{@thm_surface_variant}"
set -g copy-mode-current-match-style "fg=#{@thm_bg},bg=#{@thm_primary},bold"

# --- Basic Configuration ---
set -g mouse on
set -g base-index 1
setw -g mode-keys vi
set -sg escape-time 0
set -g focus-events on
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ",xterm-kitty:RGB"
set -ga terminal-overrides ",kitty:RGB"
set -ga terminal-overrides ",alacritty:RGB"
set -ga terminal-overrides ",tmux-256color:RGB"
set -g default-terminal "tmux-256color"
set-window-option -g xterm-keys on

# Switch panes
bind -n C-k select-pane -U
bind -n C-j select-pane -D
bind -n C-h select-pane -L
bind -n C-l select-pane -R

# Copy to system clipboard (Wayland or X11)
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'if [ -n "$WAYLAND_DISPLAY" ]; then wl-copy; else xclip -in -selection clipboard; fi'

# reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded!"
